### PR TITLE
Falling back to GAE import of endpoints.

### LINKED ISSUE #131: Endpoints isn't included in Managed VMs
Endpoints is not included in the standard Python runtime. ([link](https://cloud.google.com/appengine/docs/managed-vms/#standard_runtimes))

Additionally, gcloud (needed for VM) ignores the `libraries` section in app.yaml. As a result, `endpoints` cannot be directly imported to the project. Thus, the project fails at runtime because of [line 15](https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/c4e0be48dea2b85e0c91c9f5c8bdcb44d2605e91/endpoints_proto_datastore/ndb/model.py#L15).

Two ways to fix:

1. (Preferred) Add endpoints to standard runtime in the Google-supplied Dockerfile.
2. Replace line 15 with: 
```py
try:
    import endpoints
except ImportError:
    from google.appengine.ext import endpoints
```

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #131.

/cc @kdeus @bekt

### CODE REVIEW

**Comment by dhermes** [comment]
I'm not 100% sure this should be merged. From #131 it seems that 

```
(Preferred) Add endpoints to standard runtime in the Google-supplied Dockerfile.
```

would be the best fix.

@kdeus WDYT?

**Comment by Bekt** [comment]
:+1: lgtm

**Comment by kdeus** [comment]
I agree adding it to the standard runtime would be a better fix, but in the
meantime, I'm fine with this as a workaround.  LGTM.

**Comment by dhermes** [comment]
@kdeus I filed #133 in case you guys ever get things sorted out.

**Pull request merged**
